"""empty message

Revision ID: aca150486281
Revises: 
Create Date: 2024-12-01 21:20:58.572729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aca150486281'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('peer_number', sa.String(length=255), nullable=False),
    sa.Column('last_message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['last_message_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['line.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('line',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('number', sa.String(length=255), nullable=False),
    sa.Column('sim_slot', sa.Enum('1', '2'), nullable=False),
    sa.Column('device_mark', sa.String(length=255), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.Enum('IN', 'OUT', name='messagetype'), nullable=False),
    sa.Column('status', sa.Enum('SENDING', 'SENT', 'RECEIVED', 'READ', 'ERROR', name='messagestatus'), nullable=False),
    sa.Column('content', sa.String(length=511), nullable=False),
    sa.Column('display_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['line.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('line')
    op.drop_table('conversation')
    # ### end Alembic commands ###
